# Generated by Django 2.0.5 on 2018-08-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='videos_like',
            field=models.ManyToManyField(blank=True, related_name='vid_categories', to='videos.Video'),
        ),
    ]
