# Generated by Django 2.0.5 on 2018-08-30 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_taggedvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taggedvideo',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='taggedvideo',
            name='tag',
        ),
        migrations.DeleteModel(
            name='TaggedVideo',
        ),
    ]
