# Generated by Django 2.0.5 on 2018-08-30 03:09

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_taggedvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='videos.TaggedVideo', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
