# Generated by Django 2.0.5 on 2018-09-01 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_auto_20180830_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipbook',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='videos.Video'),
        ),
    ]
