# Generated by Django 2.0.5 on 2018-09-01 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_auto_20180901_0226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='videos_like',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
